# Generated by Django 6.0 on 2026-01-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('car_number', models.IntegerField()),
                ('chassis_number', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'car',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CarPart',
            fields=[
                ('car_part_id', models.AutoField(primary_key=True, serialize=False)),
                ('installed_at', models.DateTimeField()),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('mileage', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'car_part',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CarSession',
            fields=[
                ('car_session_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'car_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('garage_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=100)),
                ('season_year', models.IntegerField()),
            ],
            options={
                'db_table': 'garage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GarageBay',
            fields=[
                ('bay_id', models.AutoField(primary_key=True, serialize=False)),
                ('bay_number', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'garage_bay',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('part_id', models.AutoField(primary_key=True, serialize=False)),
                ('part_type', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('fia_lifecycle_limit', models.IntegerField(blank=True, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'part',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('certification_level', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'person',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('race_name', models.CharField(max_length=100)),
                ('session_type', models.CharField(max_length=10)),
                ('session_date', models.DateField()),
            ],
            options={
                'db_table': 'session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('principal_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'team',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TelemetrySession',
            fields=[
                ('telemetry_id', models.AutoField(primary_key=True, serialize=False)),
                ('data_location', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'telemetry_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkAssignment',
            fields=[
                ('work_assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'work_assignment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('work_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'work_order',
                'managed': False,
            },
        ),
    ]
