# Generated by Django 6.0 on 2026-01-12 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('part_id', models.AutoField(primary_key=True, serialize=False)),
                ('part_type', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('fia_lifecycle_limit', models.IntegerField(blank=True, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'part',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('race_name', models.CharField(max_length=100)),
                ('session_type', models.CharField(max_length=10)),
                ('session_date', models.DateField()),
            ],
            options={
                'db_table': 'session',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('principal_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'team',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('car_number', models.IntegerField()),
                ('chassis_number', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(max_length=50)),
                ('team', models.ForeignKey(db_column='team_id', on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='garage.team')),
            ],
            options={
                'db_table': 'car',
            },
        ),
        migrations.CreateModel(
            name='CarPart',
            fields=[
                ('car_part_id', models.AutoField(primary_key=True, serialize=False)),
                ('installed_at', models.DateTimeField()),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('mileage', models.IntegerField(blank=True, null=True)),
                ('car', models.ForeignKey(db_column='car_id', on_delete=django.db.models.deletion.CASCADE, related_name='car_parts', to='garage.car')),
                ('part', models.ForeignKey(db_column='part_id', on_delete=django.db.models.deletion.CASCADE, related_name='car_parts', to='garage.part')),
            ],
            options={
                'db_table': 'car_part',
            },
        ),
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('garage_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=100)),
                ('season_year', models.IntegerField()),
                ('team', models.ForeignKey(db_column='team_id', on_delete=django.db.models.deletion.CASCADE, related_name='garages', to='garage.team')),
            ],
            options={
                'db_table': 'garage',
            },
        ),
        migrations.CreateModel(
            name='GarageBay',
            fields=[
                ('bay_id', models.AutoField(primary_key=True, serialize=False)),
                ('bay_number', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('garage', models.ForeignKey(db_column='garage_id', on_delete=django.db.models.deletion.CASCADE, related_name='bays', to='garage.garage')),
            ],
            options={
                'db_table': 'garage_bay',
            },
        ),
        migrations.CreateModel(
            name='CarSession',
            fields=[
                ('car_session_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
                ('bay', models.ForeignKey(blank=True, db_column='bay_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_sessions', to='garage.garagebay')),
                ('car', models.ForeignKey(db_column='car_id', on_delete=django.db.models.deletion.CASCADE, related_name='car_sessions', to='garage.car')),
                ('session', models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, related_name='car_sessions', to='garage.session')),
            ],
            options={
                'db_table': 'car_session',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('certification_level', models.CharField(blank=True, max_length=50, null=True)),
                ('team', models.ForeignKey(db_column='team_id', on_delete=django.db.models.deletion.CASCADE, related_name='people', to='garage.team')),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.CreateModel(
            name='TelemetrySession',
            fields=[
                ('telemetry_id', models.AutoField(primary_key=True, serialize=False)),
                ('data_location', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('car_session', models.ForeignKey(db_column='car_session_id', on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_sessions', to='garage.carsession')),
            ],
            options={
                'db_table': 'telemetry_session',
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('work_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('car', models.ForeignKey(db_column='car_id', on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='garage.car')),
                ('session', models.ForeignKey(blank=True, db_column='session_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='garage.session')),
            ],
            options={
                'db_table': 'work_order',
            },
        ),
        migrations.CreateModel(
            name='WorkAssignment',
            fields=[
                ('person', models.ForeignKey(db_column='person_id', on_delete=django.db.models.deletion.CASCADE, related_name='work_assignments', to='garage.person')),
                ('work_assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=50)),
                ('work_order', models.ForeignKey(db_column='work_order_id', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='garage.work_order')),
            ],
            options={
                'db_table': 'work_assignment',
            },
        ),
    ]
